# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c26f0ac2523ac445d72980828322088093dc683ce05fef5d7457cc98a1dcbcf60206df1b373375911157460aca49e3e3fcb95b6e28c444c1d22d13ba5cc7121

test:
  secret_key_base: 09c33380a7a65eaae019df5f8ab2beca0902747fe672298900ab2ddd11e624f306bc757245b373ff8a00d4bcdadc9286322ea6d517c7d440629b9980474ad2da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
